name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  rspec:
    strategy:
      matrix:
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
        rails:
          - '5.1'
          - '5.2'
          - '6.0'
          - '6.1'

    runs-on: ubuntu-latest

    name: RSpec (Rails ${{ matrix.rails }}) (Ruby ${{ matrix.ruby }})

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Test
        run: docker-compose run --rm rspec bundle exec appraisal rails-${{ matrix.rails }} rspec
