name: Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  rspec:
    strategy:
      matrix:
        rails:
          - '5.1'
          - '5.2'
          - '6.0'
          - '6.1'

    runs-on: ubuntu-latest

    name: RSpec (Rails ${{ matrix.rails }})

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: docker-compose run --rm rspec bundle exec appraisal rails-${{ matrix.rails }} rspec
