name: Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: docker-compose run --rm rspec
